{{- if and .Values.frontend.enabled .Values.frontend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "estatewise.componentName" (dict "root" . "component" "frontend") }}-pdb
  namespace: {{ include "estatewise.namespace" . }}
  labels:
    {{- include "estatewise.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "estatewise.selectorLabels" (dict "root" . "component" "frontend") | nindent 6 }}
  unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}
