{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ include "estatewise.namespace" . }}
  labels:
    {{- include "estatewise.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }}
