apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: estatewise
resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
